<?php

/**
 * Snappy, a micro framework for PHP.
 *
 * @author Alexander Gailey-White <alex@gailey-white.com>
 *
 * This file is part of Snappy.
 *
 * Snappy is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * Snappy is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with Snappy.  If not, see <http://www.gnu.org/licenses/>.
 */

namespace Snappy\Plugin;

use Snappy\Lib\Route;
use Snappy\Lib\Event;
use Snappy\Lib\Watchdog;

class Example {
	private static $path;

	public static function init() {
		self::$path = SNAPPY_PLUGIN_PATH . 'example' . DS;

		/**
		 * Route rules can be automatically loaded at runtime after being stored with Route::save()
		 */
		Route::add( 'example.index', '', null, '\Snappy\Plugin\Example::content' );
		Route::add(

			// Route name
			'example.page',

			// Route path relative to Snappy framework, with regex pattern placeholder [page]
			'[page]',
			array(

				// Pattern for [page]. Route data is accessed using Route::getParam('page');
				'page' => '[a-z]+',

				// Additional route meta[data] set if route matched.
				'foo' => 'bar'
			),

			// Route callback if matched
			'\Snappy\Plugin\Example::content'
		);
	}

	/**
	 * Callback for route matches...
	 */
	public static function content() {

		// Do we have a 'page' parameter?
		$page = Route::getParam( 'page' );
		if( empty( $page ) ) {
			$page = 'index';
			Watchdog::set(
				__('Your framework environment has no configuration. So here is some content generated by <strong>Snappy\Plugin\Example</strong>'),
				0,
				'example',
				Watchdog::INFORMATION
			);
		} elseif( $page == 'index' )
			\Snappy::response()->location();

		// Capture the controller's output
		$content = \Snappy::capture( 'plugin.example.page.' . $page );
		if( is_string( $content ) ) {

			// Add to the output document
			\Snappy::response()->appendBody( $content );
		} else {
			\Snappy::response()->status(404);
		}
	}

	public static function beforeDocumentGetHead() {

		// Set some document properties
		$return = \Snappy::response();
		$return->addStyle( 'plugin/example/asset/css/example.css' );
		$return->addScript( 'plugin/example/asset/js/main.js' );
		$return->addScript( 'lib/snappy.js' );
		$return->setVpWidth( 0 );
//		$return->addStyle( 'https://fonts.googleapis.com/css?family=Raleway:400,700' );
		$return->setTitleSeparator( ' &bull; ' );
		$return->setTitle( 'Snappy, a PHP micro framework for whatever.' );
		$return->setDescription( 'A PHP micro framework for whatever.' );
	}

	public static function beforeDocumentGetBody() {
		//<header><main><div><a href="' . SNAPPY_URL . '" class="logo">SNAPPY</a></div></main></header>
		$return = \Snappy::response();
		$return->prependBody( '<main>' );
		$return->appendBody( '</main>' );
	}
}

// Establish the plugin's routes
Event::set( 'init', '\Snappy\Plugin\Example::init' );

// Document header
Event::set( 'beforeDocumentGetHead', '\Snappy\Plugin\Example::beforeDocumentGetHead' );

// Document footer
Event::set( 'beforeDocumentGetBody', '\Snappy\Plugin\Example::beforeDocumentGetBody' );

// Example event for files in the request, they have been processed in Http::init() and are ready to handle
//Event::set( 'requestHasFiles', function ( $files ) {
//	var_dump( $files ); exit;
//} );