<?php

/**
 * Snappy, a micro framework for PHP.
 *
 * @author Alexander Gailey-White <alex@gailey-white.com>
 *
 * This file is part of Snappy.
 *
 * Snappy is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * Snappy is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with Snappy.  If not, see <http://www.gnu.org/licenses/>.
 */

\Snappy::response()->prependTitle( __( 'Welcome' ) );

//echo Sanitize::forHtml(Snappy::request()->query('aaa'));

?>
<div>
	<h1>Snappy, a micro framework for PHP.</h1>
	<p>Here is a sample page router, generated by <strong>Snappy\Plugin\Example</strong>. For examples on what Snappy can do,
		visit <a href="https://gailey-white.com/snappy-php-framework">this post</a> on my blog.</p>
	<p class="cta"><strong><?php ___('User environment') ?> (<a href="./user">modify</a>)</strong><br><?php ___( 'Language' ) ?> (<?php echo \Snappy::locale()->getLocale() ?>)</p>
	<p>
		<a href="./request">JSON API</a>
	</p>
</div>