<?php

/**
 * Deft, a micro framework for PHP.
 *
 * @author Alexander Gailey-White <alex@gailey-white.com>
 *
 * This file is part of Deft.
 *
 * Deft is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * Deft is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with Deft.  If not, see <http://www.gnu.org/licenses/>.
 */

namespace Deft\Plugin;

class Example extends \Deft\Lib\Plugin {
	private static $path;

	public static function init() {
		self::$path = DEFT_PLUGIN_PATH . DS . 'example' . DS;

		\Deft::route()->cli( 'example.cli', 'example', null, function(){
			\Deft::log()->info(__('Hello world!'));
			\Deft::response()->appendBody('Hello world!');
		});

		/**
		 * Route rules can be automatically loaded at runtime after being stored with \Deft::route()->save()
		 */
		\Deft::route()->api( 'example.json', 'example/json', null, function(){
			\Deft::response()->buffer([
				'exampleJson' => [
					'reqTime' => \Deft\Lib\Sanitize::forHtml(time())
				]
			]);
		});

		\Deft::route()->http( 'example.index', '', null, '\Deft\Plugin\Example::content' );
		\Deft::route()->http(

			// Route name
			'example.page',

			// Route path relative to Deft framework, with regex pattern placeholder [page]
			'example/[page]',
			array(

				// Pattern for [page]. Route data is accessed using \Deft::route()->getParam('page');
				'page' => '[a-z]+',//'[index|request|response|users]+',

				// Additional route meta[data] set if route matched.
				'foo' => 'bar'
			),

			// Route callback if matched
			'\Deft\Plugin\Example::content'
		);
	}

	/**
	 * Callback for route matches...
	 */
	public static function content() {
		$res = \Deft::response();
		$page = \Deft::route()->current()->data['page'];
		if( empty( $page ) ) {
			$page = 'index';
			\Deft::log()->add(
				__('Your framework environment has not been configured to do anything special yet. So here is some content generated by <strong>Deft\Plugin\Example</strong>'),
				'example',
				\Deft\Lib\Log::INFORMATION
			);
		} elseif( $page == 'index' )
			$res->location();

		// Get response handle
		$res->addStyle( 'plugin/example/asset/example.css' );
		$res->addScript( 'plugin/example/asset/main.js' );
		$res->addScript( 'deft.js' );
		$res->addScriptContent( "document.body.className=document.body.className.replace('no-js','js');" );
		$res->setVpWidth( 0 );
		$res->addStyle( 'https://fonts.googleapis.com/css?family=Raleway:400,700' );
		$res->setTitleSeparator( ' &bull; ' );
		$res->setTitle( 'Deft, a PHP & JS framework' );
		$res->setDescription( 'Another framework, another approach' );
		$res->addMeta('plugin.example', '1');

		// Capture the output
		$content = \Deft::capture( 'plugin.example.page.' . $page );
		if( is_string( $content ) ) {
			$res->appendBody($content);
			$res->prependBody( '<main>' );
			$res->appendBody( '</main>' );
		}
	}
}

// Establish the plugin's routes
\Deft::event()->set( 'init', '\Deft\Plugin\Example::init' );
